Add support for WIZNET5K ssl
adafruit/Adafruit_CircuitPython_ConnectionManager pull request #9
Opened 2024-04-20 23:09 UTC by justmobilize

2024-04-20 23:17 UTC, justmobilize commented on adafruit_connection_manager.py
> +            if pool.SOCK_STREAM == 1 and cp_version[0] >= 9:
This was my best thought on checking the version. If there is a better way, let me know (I also hope ssl everywhere doesn't go out in a revision...)

2024-04-20 23:30 UTC, justmobilize commented
@anecdata if you have time, would you be willing to try this?

2024-04-24 19:42 UTC, anecdata commented
I'm having trouble geting the right pieces together for this. Here's what's installed:
`Adafruit CircuitPython 9.1.0-beta.0-27-g4ede914d45 on 2024-04-17; FeatherS3 with ESP32S3` (PR #8954)
`adafruit_requests` v3.2.5 (latest)
`adafruit_connection_manager` (this PR #9)
`adafruit_wiznet5k` v5.2.0 (includes #157, but not #151)

<details>
<summary>code...</summary>

```py
import traceback
import ssl
import board
import digitalio
from adafruit_wiznet5k.adafruit_wiznet5k import WIZNET5K
import adafruit_requests
import adafruit_connection_manager

TEXT_URL = "https://httpbin.org/get"

spi_bus = board.SPI()
cs = digitalio.DigitalInOut(board.A4)
mac = f'de:ad:be:ef:fe:{(252):02x}'  # need this to avoid DHCP collisions
radio = WIZNET5K(spi_bus, cs, mac=mac, debug=False)
pool = adafruit_connection_manager.get_radio_socketpool(radio)
ssl_context = adafruit_connection_manager.get_radio_ssl_context(radio)
requests = adafruit_requests.Session(pool, ssl_context)

while True:
    print(f"Fetching from {TEXT_URL} ... ", end="")
    with requests.get(TEXT_URL) as resp:
        print(f'{resp.status_code}')
    time.sleep(5)
```
</details>

result:
```
Fetching from https://httpbin.org/get ... Traceback (most recent call last):
  File "code.py", line 23, in <module>
  File "adafruit_requests.py", line 591, in get
  File "adafruit_requests.py", line 525, in request
  File "adafruit_connection_manager.py", line 256, in get_socket
  File "adafruit_wiznet5k/adafruit_wiznet5k_socket.py", line 195, in getaddrinfo
  File "adafruit_wiznet5k/adafruit_wiznet5k_socket.py", line 210, in gethostbyname
AttributeError: 'NoneType' object has no attribute 'get_host_by_name'
```

I haven't used CM too much yet, maybe there's something wrong in the code.

2024-04-24 20:20 UTC, justmobilize commented
@anecdata I found the issue (working on too many things at the same time). I'll update this PR tonight

2024-04-24 21:52 UTC, anecdata commented
Yes, I fully understand, there are so many inter-related changes going on, it's hard to keep track of what goes with what.

2024-04-24 22:14 UTC, justmobilize commented
Especially when it's one's own fault. I keep doing things here like I do professionally and thinking things will get merged and released quickly...

2024-04-24 23:54 UTC, justmobilize commented
@anecdata this should work now... Sorry about that

2024-04-25 02:26 UTC, anecdata commented
That did it... "200 OK" every 5 seconds :-)

2024-04-25 18:11 UTC, anecdata approved these changes

2024-04-25 18:48 UTC, dhalbert requested changes
Not tested. Just one style thing.

2024-04-25 18:48 UTC, dhalbert commented on adafruit_connection_manager.py
> +                    """SSL not on board default to fake_ssl_context"""
```suggestion
                    # if SSL not on board, default to fake_ssl_context
```

2024-04-25 19:09 UTC, justmobilize commented
@dhalbert updated

2024-04-25 20:11 UTC, dhalbert approved these changes
Thanks!

2024-04-25 20:11 UTC, merged